workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      node: 18.18.2
      java: 17
      vars:
        EXPO_PUBLIC_API_BASE: "http://76.13.100.119:4000"
        GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.caching=true"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install Android SDK/NDK
        script: |
          sdkmanager --version
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0" "ndk;23.1.7779620"
      - name: Build shared package
        script: |
          npm run build --workspace packages/shared
      - name: Build debug APK
        script: |
          cd apps/mobile/android
          chmod +x gradlew
          ./gradlew assembleDebug --build-cache \
            -Pandroid.compileSdkVersion=33 \
            -Pandroid.targetSdkVersion=33 \
            -Pandroid.buildToolsVersion=33.0.0 \
            -Pandroid.ndkVersion=23.1.7779620
    artifacts:
      - apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk
